### PR TITLE
RFC Breaking change - implement cross module interfaces

### PR DESCRIPTION
**Pull request by KlausC**
This PR implements - just to see if it works - the thoughts found in this issues thread: https://github.com/tk3369/BinaryTraits.jl/issues/39#issuecomment-618276041

### CODE REVIEW

**Comment by tk3369** [comment]
Looks awesome! 

Now that `check` function does not need the module argument anymore, maybe we should just delete the `@check` macro and switch the API back to using `check` function again. Just another massive search and replace again 😉

Let me know when you're done with this PR.  I'd like to "battle test" it -- an idea is to take [Tables.jl](https://juliadata.github.io/Tables.jl/dev/), define its interfaces, and verify a bunch of its [implementations](https://github.com/JuliaData/Tables.jl/blob/master/INTEGRATIONS.md).

**Comment by tk3369** [comment]
Mmm... It turns out that Tables.jl is a very bad example to test with.  It's using duck typing to provide fallback implementations for interface functions.  Maybe I'll just find a better test case...

**Comment by KlausC** [comment]
As for me, this PR is finished.

**Comment by tk3369** [comment]
To speed this up, I have merged this PR into a separate branch first.  I am going to make few documentation edits and merge into master.

**Pull request merged**
